[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Development configuration
[dev]
  command = "npm run dev"  # Explicitly tell Netlify which command to run
  port = 3000             # Port to use for the dev server
  targetPort = 5173       # Vite's default port that Netlify should proxy to
  autoLaunch = true       # Open browser automatically

# Function configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# Runtime configuration - Node.js 18
[build.environment]
  NODE_VERSION = "18"

# Función específica
[[redirects]]
  from = "/api/processTrends*"
  to = "/.netlify/functions/processTrends/:splat"
  status = 200
  force = true 

# SPA redirect rule - This ensures that all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 